### ISSUE TITLE
Allow dns as well as IP

### ISSUE THREAD

**Issue by counterfitninja** [jhead/phantom#1]
Could you add DNS as well as IP address. I'm using Azure as a host and the IP will change overtime so its easier to use a DDNS entry directly.

**Comment by jhead** [comment]
Hey @counterfitninja! Thanks for the idea. Are you suggesting that you would supply a DNS hostname when it starts up and it continually resolves the IP over time, in case the IP changes while phantom is running?

Right now it supports DNS but it resolves the IP once at startup, so if the IP changes, it won't get the new one without restarting it.

**Comment by counterfitninja** [comment]
Hmm I thought I tried starting with a host name and it failed but it was a while ago. If that already works that's enough 😂 sorry.

**Comment by counterfitninja** [comment]
I have just tried again and it looks like its only allowing ip only. 
![capture](https://user-images.githubusercontent.com/4258903/46248509-f6dd8180-c411-11e8-8f2f-07f890bc33cb.PNG)

**Comment by jhead** [comment]
Try `azure.com:19316` as one argument 🙂

**Comment by counterfitninja** [comment]
Ok No idea why i managed to get it to fail the first time. Tis working now...
