### ISSUE TITLE
multiple servers

### ISSUE THREAD

**Issue by timriker** [jhead/phantom#11]
Would it be possible to support multiple servers? Each on it's own port perhaps?
Right now, due to the other bug, I can't test multiple instances of phantom.

Side note: I'd suggest a different name. bedrockproxy? mcpeproxy? mcbproxy?

Seems to work well, thanks!

**Comment by jhead** [comment]
Hey @timriker, this should be possible with multiple instances of the proxy. We're planning to release a small UI that simplifies the setup and supporting multiple servers.

It used to be bedrock-proxy or something like that, but that was no fun. The best projects have irrelevant names ;)

**Comment by jhead** [comment]
Late reply but the latest version of phantom supports randomized ports by default for multiple instances, without requiring any special configuration.
