### ISSUE TITLE
Unable to join world

### ISSUE THREAD

**Issue by Zeonnova** [jhead/phantom#110]
When i try joining a server thats has a diffrent port/regular port it saids unable to join world i can join some servers but not certain ones @jhead @scr34m @jaredible @nkelemen18

**Comment by IceCruelStuff** [comment]
You don't need to ping people

**Comment by joshuaxlino** [comment]
> When i try joining a server thats has a diffrent port/regular port it saids unable to join world i can join some servers but not certain ones @jhead @scr34m @jaredible @nkelemen18 
> 
> 

An easy fix should be: join this server via phantom: grandtheft.mcpe.me:19132 . Once you connect, enter the command in chat: /transferserver (server ip no port included)

**Comment by jhead** [comment]
Hey @Zeonnova, my best guess would be that phantom isn't compatible with the software that those servers are running. For example, there's a known bug in phantom that prevents it from working with Nukkit-style servers, while Bedrock and PocketMine work fine. 

that transferserver command might work though 😄
