### ISSUE TITLE
Feature request or help needed

### ISSUE THREAD

**Issue by suerion** [jhead/phantom#112]
Hey, if this is not a feature yet, please try to add Realm connections,

If this is a feature, how could i join an realm from realms.gg? 

I had an invitecode, but i don't know, how to join on PS4, i would not play on an other server

I hope, someone could help me.

**Comment by joshuaxlino** [comment]
You see, it may not be possible. I have tried joining via ps4 to a realm and it simply said "your device does not support this feature" and unlike servers, that message does not appear.

**Comment by jhead** [comment]
Hey @suerion, apologies for the delay. I think #125 covers the same feature request. There's no support for this yet but I can definitely look into it.
