### ISSUE TITLE
Im a little confused

### ISSUE THREAD

**Issue by DivineStag** [jhead/phantom#114]
Hi! So happy this is working!

However I don't know much about code... ive done the first line: _phantom_-windows.exe 'sever and port'
Then it shows up on my friends list which is great and I can go on the server! However I have no idea what the rest of the code means. 
![image](https://user-images.githubusercontent.com/69634401/90242910-c9dbc180-de25-11ea-838d-0f4d15394d5e.png)

Any help will be great!

**Comment by joshuaxlino** [comment]
> Hi! So happy this is working!
> 
> 
> 
> However I don't know much about code... ive done the first line: _phantom_-windows.exe 'sever and port'
> 
> Then it shows up on my friends list which is great and I can go on the server! However I have no idea what the rest of the code means. 
> 
> ![image](https://user-images.githubusercontent.com/69634401/90242910-c9dbc180-de25-11ea-838d-0f4d15394d5e.png)
> 
> 
> 
> Any help will be great!
> 
> 

I would suggest my setup, on the latest version of phantom: -workers 16 -6 -bind_port 19133 -server (server ip)

**Comment by jhead** [comment]
Hey @DivineStag! The other lines are just examples for people looking to reconfigure phantom based on their Minecraft server's setup. It sounds like you got everything working with the simplest command, so that's all you should need 😄

**Comment by DivineStag** [comment]
Oh that’s great!

Thanks for the help!

- A. Norris
________________________________
