### ISSUE TITLE
How can we make Phantom work with NukkitX?

### ISSUE THREAD

**Issue by Leadhood** [jhead/phantom#116]
Phantom seems to work but then can't load the world. Is there any clue as to where things go wrong?

**Comment by jhead** [comment]
Hey @Leadhood, thanks for the +1 on this issue. We've got an existing one over at #16 tracking this incompatibility and any progress on fixing it.

**Comment by jhead** [comment]
Hey @Leadhood, I just tested this again recently and wasn't able to reproduce. It appears that phantom works with Nukkit now. Could you try again and let me know if you still run into any issues?

**Comment by Leadhood** [comment]
Hey @jhead thank you for your time and your reply! Since my question I moved to use the bedrock server found at Minecraft.net

So I just compiled the latest version of nukkitX but when I tried to play (without Phantom) I got a "server out of date" message.... I do not have much time to look further into this problem, but I will try it later.
