### ISSUE TITLE
Phantom run on android?

### ISSUE THREAD

**Issue by D4RKT33N** [jhead/phantom#119]
Is there any Option to run the Phantom application on Android?

**Comment by prestige2** [comment]
no, but I think the Linux version can run on termux app on android but idk

**Comment by BadWolf22** [comment]
@D4RKT33N There is no native Android app for Phantom as of yet, although I do hope to possibly work on this one day. For now, you can run it in Termux as @prestige2 said if you refer to [this issue](https://github.com/jhead/phantom/issues/111#issuecomment-686714910).

**Comment by Tanishq-Banyal** [comment]
> Is there any Option to run the Phantom application on Android?

Yes there is a app called "MC Server Connector" on android play store. It does the same thing anad even has a nice gui
