### ISSUE TITLE
Building on mac

### ISSUE THREAD

**Issue by waknauss** [jhead/phantom#12]
Good Day,
I couldn't get this to build on my Mac. I'm not experienced enough with Go so I'm sure its something I'm doing wrong. Here is a screenshot:

![Screen Shot 2019-07-01 at 12 40 08 PM](https://user-images.githubusercontent.com/20912626/60452833-7e545d00-9bfd-11e9-9e8a-3ea26ea742f2.png)

**Comment by pupshadow** [comment]
im having a problem and it is error 127

**Comment by jhead** [comment]
Hey there! Golang expects you to have the source in a specific path.
Try moving it to: `$HOME/go/src/github.com/jhead/phantom`

This doesn't happen with the new Go modules, but I haven't gotten around to using them yet.
