### ISSUE TITLE
(Feature Request) Xbox Signin/spoof

### ISSUE THREAD

**Issue by Tanishq-Banyal** [jhead/phantom#121]
Please add option to signin to xbox live 🙏🙏

In theory it should work like this :-

Phantom would imitate MCPE signature and open a browser window for signin

After signin it would modify request coming from a lan player and tell the server that the request is coming from that account (which it earlier signed into)

It will help cracked windows 10 Edition players to play on premium servers

**Comment by imnotjack91** [comment]
For that to have a hope of working, you would have to have the game licensed on the account you sign in to.

By "cracked" you mean modded or unlicensed full version?

**Comment by Tanishq-Banyal** [comment]
> For that to have a hope of working, you would have to have the game licensed on the account you sign in to.
> 
> By "cracked" you mean modded or unlicensed full version?

**Comment by Dreamedc2015** [comment]
Please I beg don't add this
you would just bring more hackers who have had there purchase blocked by Microsoft please don't detriment the mcbe community-run servers
