### ISSUE TITLE
I'm on mac and have no idea how to use this

### ISSUE THREAD

**Issue by MysteryMan36090** [jhead/phantom#13]
I'm trying to use this on my mac and all I see when I open the file is a bunch of random characters. Can you please add instructions. Thanks. (:

**Comment by pupshadow** [comment]
BUMP same here cant open or use it in any way.

**Comment by jhead** [comment]
Hey @MysteryMan36090! Check out the usage section of the readme. You'll want to open the Terminal app and navigate to where you downloaded the file, then run the commands.

Let me know if you need any more help.

<img width="682" alt="Screen Shot 2019-07-27 at 12 17 44 PM" src="https://user-images.githubusercontent.com/360153/61998695-938ba280-b068-11e9-8383-42410180c84e.png">
