### ISSUE TITLE
Server says "Outdated"

### ISSUE THREAD

**Issue by danielsenorjan** [jhead/phantom#139]
Hi.

My brother is trying to use phantom to connect to my Minecraft server hosted on Shockbyte. We had it working for weeks without issues, but the last few days he gets the Outdated message when trying to connect. The server console shows nothing, and the phantom console shows that he's connecting but nothing else.
We've tried several versions of GeyserMC, phantom and tried using spigot instead of paper, with absolutely no luck.
Neither Java Edition nor the PS4 version of Minecraft has updated since before we experienced the issue, so that should not play a part.

**Comment by jhead** [comment]
Hey @danielsenorjan! It sounds like your Shockbyte server may have updated in the meantime and your clients (PS4) weren't updated yet. There's often a delay between game/server updates. Either way, phantom doesn't need to be updated to get it working with a newer version of Minecraft.

Let me know if you're still having trouble!
