### ISSUE TITLE
Requirements for hardware?

### ISSUE THREAD

**Issue by DIYglenn** [jhead/phantom#14]
Sorry for creating an issue for my question. Sub Reddit was archived. 

Will this work on a old 1st gen Raspberry Pi B? I have a couple of those laying around, would be great to just set up at friends’ house for them to join from Xbox.

**Comment by jhead** [comment]
Hey @DIYglenn, as long as you can install Linux on there, you should give it a shot. I looked up the model B hardware [here](https://elinux.org/RPi_HardwareHistory) and it shows an ARMv6 compatible processor. I've included ARMv6 binaries on our releases page, so try that out and let me know if you run into any issues. You shouldn't need to build/recompile it on the device.

```bash
$ curl -sLO https://github.com/jhead/phantom/releases/download/v0.1.2/phantom-linux-arm6
$ ./phantom-linux-arm6
```

**Comment by DIYglenn** [comment]
Thanks! I'll give it a go when my friend get back from vacation.
