### ISSUE TITLE
Syntax error: newline unexpected

### ISSUE THREAD

**Issue by Scheeringa1** [jhead/phantom#140]
I used your program all the time so that my brother could join our server from him XBox. Bravo! 

I had to reinstall everything on the Raspberry Pi because of a corrupted SD card, and now I get the following error:
Syntax error: newline unexpected

I tried using some older versions, and still no bueno. What am I doing wrong?

**Comment by ItIsFelix** [comment]
You maybe need to post your command here.

**Comment by Scheeringa1** [comment]
I ended up figuring it out. For some reason, when I manually typed the address using the wget command, it wasn't downloading the file. When I copied and pasted the address into Putty, it pulled the file with no issues. Must be some kind of noob error?
