### ISSUE TITLE
Update 2.21 (PS4 and XBox) Server doesn't show up

### ISSUE THREAD

**Issue by ItIsFelix** [jhead/phantom#143]
After updating the client software to 2.21(PS4) the server doesn't show up anymore. Same problem on XBox.

**Comment by bjur4676** [comment]
I have the same Problem. After the update the sever is not in the list.

**Comment by ItIsFelix** [comment]
> After updating the client software to 2.21(PS4) the server doesn't show up anymore. Same problem on XBox.

I'm running the phantom ARM version on Raspberry Pi

**Comment by bjur4676** [comment]
> > After updating the client software to 2.21(PS4) the server doesn't show up anymore. Same problem on XBox.
> 
> I'm running the phantom ARM version on Raspberry Pi

My phantom version runs on my windows PC.

**Comment by bjur4676** [comment]
I had fixed the Problem. The Script returns a wrong Server Version. The Script return Server Version 1.6.0, but the Client want now a newer Version. So I had change the return value to 1.16.210 in Line 201 in internal/proxy/proxy.go. 

After the change was my connection successful.

**Comment by ItIsFelix** [comment]
> I had fixed the Problem. The Script returns a wrong Server Version. The Script return Server Version 1.6.0, but the Client want now a newer Version. So I had change the return value to 1.16.210 in Line 201 in internal/proxy/proxy.go.
> 
> After the change was my connection successful.



> I had fed the Problem. The Script returns a wrong Server Version. The Script return Server Version 1.6.0, but the Client want now a newer Version. So I had change the return value to 1.16.210 in Line 201 in internal/proxy/proxy.go.
> 
> After the change was my connection successful.

I could need more Info how to fix it.
I'm not familiar with building the application. 
In line 201 I see the following:

![SmartSelect_20210311-222727_Chrome](https://user-images.githubusercontent.com/29043104/110857445-2702fd00-82b9-11eb-9558-828ae2659f91.jpg)

**Comment by bjur4676** [comment]
I can send you the compiled linux or .exe version ? I have an other state of the script on my PC. I think it's from another fork. 
So if you want my running version, I would give you an download link for Linux or Windows. 

I have only test the windows-version :)

**Comment by bjur4676** [comment]
> > I had fixed the Problem. The Script returns a wrong Server Version. The Script return Server Version 1.6.0, but the Client want now a newer Version. So I had change the return value to 1.16.210 in Line 201 in internal/proxy/proxy.go.
> > After the change was my connection successful.
> 
> > I had fed the Problem. The Script returns a wrong Server Version. The Script return Server Version 1.6.0, but the Client want now a newer Version. So I had change the return value to 1.16.210 in Line 201 in internal/proxy/proxy.go.
> > After the change was my connection successful.
> 
> I could need more Info how to fix it.
> I'm not familiar with building the application.
> In line 201 I see the following:
> 
> ![SmartSelect_20210311-222727_Chrome](https://user-images.githubusercontent.com/29043104/110857445-2702fd00-82b9-11eb-9558-828ae2659f91.jpg)

Here is the Link. 
[Donwload-Link](https://drive.terracloud.de/getlink/fiLWB4g7sTw4XWCHRvG5fe9b/minecraft-proxy)

**Comment by ItIsFelix** [comment]
Thanks @bjur4676 !

Unfortunately it's not working. 
`-bash: ./phantom-linux-arm7: cannot execute binary file: Exec format error`
Maybe a 64 - 32 bit problem.
I am wondering if we are the only minecraft gamers in the world using a server without Realms ;-)
I will try to learn to build the program by myself and to find the right code to change with your great hint!

**Comment by bjur4676** [comment]
> 
> 
> Thanks @bjur4676 !
> 
> Unfortunately it's not working.
> `-bash: ./phantom-linux-arm7: cannot execute binary file: Exec format error`
> Maybe a 64 - 32 bit problem.
> I am wondering if we are the only minecraft gamers in the world using a server without Realms ;-)
> I will try to learn to build the program by myself and to find the right code to change with your great hint!

Do have update the Server? I had try the master version from phantom without any changes and it works. I had update yetser day update my Server to 1.16.210.05.

**Comment by ItIsFelix** [comment]
> Do have update the Server? I had try the master version from phantom without any changes and it works. I had update yetser day update my Server to 1.16.210.05.


You are totally right.
The master version is working fine.

**Comment by ItIsFelix** [comment]
Problem was an old version of phantom. Updating server, client and phantom to the latest version solved my issue.
