### ISSUE TITLE
Can Phantom work with PS5? 

### ISSUE THREAD

**Issue by Fubble365** [jhead/phantom#147]
I've been using Phantom to connect to a server in PS4 for months and it works great. I've not got a PS5 and wondered if it can work on there. Tried connecting on PS5 and it finds the server but won't connect.

**Comment by azariah001** [comment]
technically there shouldn't be any issues as (to the best of my knowledge) there is no meaningful software difference between the PS4 and PS5. IE they didn't completely rebuild the PSOS, the majority of the changes are in UI, Hardware, and just general performance capabilities with a sprinkling of new features that can be accessed. IE the version of Minecraft on the PS5 is 99% identical to the PS4 version, ignoring any game updates that may have occurred in the interim naturally.

There is a distinct possibility however that if your server has a whitelist that your login on the PS5 has created a different UUID to the one you had on the PS4. We actually had a number of Xbox players have this happen not when moving from Xbox One to Series but actually as a result of the latest Minecraft update. The update from 1.16.201 to 1.16.210 borked ... 3 profiles. Had to edit the world file to reassociate the new UUID's to the old player data.

**Comment by jdanprosser** [comment]
Hey, I can confirm it is working perfectly fine for me on PS5

**Comment by jhead** [comment]
Hey @Fubble365, as mentioned above, there shouldn't be anything specific to PS5 that makes it incompatible with phantom. If you're still having trouble, could you post the error message you're getting, along with any info you have about the server(s) that you're connecting to?
