### ISSUE TITLE
IS there any YouTube tutorials?

### ISSUE THREAD

**Issue by D4cky** [jhead/phantom#159]
I'm quite bad at understanding what to do at this, is there any video tutorials?

**Comment by enescglyn** [comment]
https://github.com/jhead/phantom/issues/153 if you are using win 10 or 11 the software might not work but i will still tell you instructions:

1. go to releases page and download exe file
2. open the folder the download exe's contained in and shift + right click to that folder(not the exe) then click open in command prompt, open in powershell or open in windows terminal, which one shows up depends on your windows version and settings
3. in the opened box write in `phantom-windows.exe -server lax.mcbr.cubed.host:19132` (change the ip to the server ip you want)
4. check friends tab in minecraft

**Comment by 1liminal1** [comment]
https://www.youtube.com/watch?v=UEfqpKyDQ48
