### ISSUE TITLE
Compatibility Nukkit

### ISSUE THREAD

**Issue by djodjo02130** [jhead/phantom#16]
It's possible to get compatible with nukkit ?
https://github.com/NukkitX/Nukkit

**Comment by jhead** [comment]
Hey @djodjo02130! Sorry for the late reply. I just tested it out and wasn't able to connect to a Nukkit server through phantom. I'll see if I can figure out why and let you know if I have a solution.

**Comment by EncryptedCurse** [comment]
Is Nukkit support still broken? I honestly wouldn't mind using something else, but my hands are a bit tied as I'm running it off a Raspberry Pi (32-bit). My friend's Xbox One can see the Phantom server (and vice versa), but it refuses to connect.

**Comment by jhead** [comment]
Hi all, it appears that phantom works with [Nukkit](https://github.com/CloudburstMC/Nukkit) now. I don't believe I changed anything to fix this specifically so maybe Nukkit had a quirk in its usage of the Bedrock protocol. In any case, I'm no long getting any errors when connecting to my own server running Nukkit or others.

Let me know if you're still running into any issues getting connected.
