### ISSUE TITLE
Build as a Bukkit, Spigot, Paper, Fabric, Forge, or Velocity plugin/mod?

### ISSUE THREAD

**Issue by teknixstuff** [jhead/phantom#167]
Could you think about making this available as a mod/plugin so it can intergrate with my current Purpur+Geyser setup better?

**Comment by jhead** [comment]
Hey @teknixstuff, I'm not sure that's possible since phantom needs to run locally (on each player's LAN) as opposed to on/near the server itself, because of the way Minecraft discovers LAN servers. If you have any specific ideas though, let me know!

**Comment by teknixstuff** [comment]
Ah. I'm using the server as a LAN server though, it would work fine, since the server is running locally! (And yes ik I can just run phantom separately, however that's annoying, especially with my current server setup)
