### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alfnicko** [jhead/phantom#17]
I am following the instructions but it is not working, the ip and port are not wrong

https://gyazo.com/48de36c91f200f79e9bece69ed247033

help is appreciated

**Comment by edgararroyo** [comment]
add the option " -server " in between phantom and the ip:port

phantom.exe -server 37.187.134.105:25584

BTW, that port # looks similar to JAVA minecraft, this is for MCPE.

**Comment by jhead** [comment]
+1

I'll correct the readme to include `-server`, but you'll need to make sure you're using a Bedrock/MCPE server such as the official Bedrock server or PocketMine.
