### ISSUE TITLE
How can I run multiple proxies?

### ISSUE THREAD

**Issue by edgararroyo** [jhead/phantom#19]
I created 2 additional virtual lans and running 3 instances

phantom -server 1.2.3.4:19132 -bind 1.0.0.0:19132
phantom -server 1.2.3.4:19133 -bind 1.0.0.1:19133
phantom -server 1.2.3.4:19134 -bind 1.0.0.2:19134

It's getting stuck at Starting idle connection handler

Apparently the -bind option is not working.

**Comment by edgararroyo** [comment]
Ok, I got them to run, but it's getting stuck at Starting idle connection handler

Apparently the -bind option is not working.

**Comment by jhead** [comment]
Hey @edgararroyo, I believe the ping packet is broadcasted from devices (i.e. xbox/PC) to your LAN but only targets port 19132. Using different IPs with the same port should work if the IPs are on the same subnet as your LAN. For example, most LANs would be 192.168.0.0/24 or 10.0.0.0/24; using 1.0.0.0/24 on either of those probably won't allow the proxy to receive the broadcasted ping packet.

Some suggestions:
- try using multiple IPs with port 19132 on all of them
- if those IPs are not on the same subnet as your LAN, try adding additional LAN IPs

lmk if you still have trouble getting it to work.

**Comment by edgararroyo** [comment]
That's exactly what I did.  I created 2 additional macvlans from my eth0 and I can vnc or ssh to these new IPs but pahntom does not listen to the pings when I use -bind.  If I omit -bind it uses the first IP and it does listen to the pings.

Example:
eth0 ip 192.168.0.10
eth1 ip 192.168.0.11
eth2 ip 192.168.0.12

If I omit -bind it works fine with 192.168.0.10, but if I use -bind 192.168.0.10 it doesn't listen.

On Sep 7, 2019 9:40 PM, Justin Head <notifications@github.com> wrote:

Hey @edgararroyo<https://github.com/edgararroyo>, I believe the ping packet is broadcasted from devices (i.e. xbox/PC) to your LAN but only targets port 19132. Using different IPs with the same port should work if the IPs are on the same subnet as your LAN. For example, most LANs would be 192.168.0.0/24 or 10.0.0.0/24; using 1.0.0.0/24 on either of those probably won't allow the proxy to receive the broadcasted ping packet.

Some suggestions:

  *   try using multiple IPs with port 19132 on all of them
  *   if those IPs are not on the same subnet as your LAN, try adding additional LAN IPs

lmk if you still have trouble getting it to work.

**Comment by edgararroyo** [comment]
This is not working
[code]root@raspberrypi:/home/pi# ps -ax | grep pha
 3181 ?        Sl     0:00 /bin/phantom-linux-arm7 -server 72.238.18.140:19132 -bind 192.168.25.115:19132
 3182 ?        Sl     0:00 /bin/phantom-linux-arm7 -server 72.238.18.140:19133 -bind 192.168.25.117:19132
 3183 ?        Sl     0:00 /bin/phantom-linux-arm7 -server 72.238.18.140:19134 -bind 192.168.25.116:19132
 3297 pts/0    S+     0:00 grep pha
root@raspberrypi:/home/pi# [/code]

But this is working
[code]root@raspberrypi:/home/pi# ps -ax | grep pha
 3308 ?        Sl     0:00 /bin/phantom-linux-arm7 -server 72.238.18.140:19132
 3315 pts/0    S+     0:00 grep pha
root@raspberrypi:/home/pi# [/code]

**Comment by edgararroyo** [comment]
Well, for now I am running 3 Ubuntu Playground dockers but I would like this to work with "-bind" so I can use a dedicated Raspberry Pi for all 3 of my PocketMine servers.

**Comment by jhead** [comment]
Hey Edgar,

I think I found the issue. `-bind` doesn't seem to work properly because the ping packets that are sent to every device on the network have a destination of x.x.x.255 (the broadcast address), and these don't seem to be forwarded to the IP used with `-bind`. Without `-bind`, the proxy listens on all addresses, which allows it to receive those ping packets.

Docker is likely different and forwards the broadcast packets down to the containers, since you're passing `--net=eth0` through -- that's probably why it works.

One solution would be for phantom to listen on 0.0.0.0:19132 (i.e. without `-bind`) with SO_REUSEADDR _and_ listen on  a separate IP/port. When it receives the broadcast ping packet, it triggers the second listener to respond from its own IP/port, so that the Bedrock/PE device knows what IP/port to talk to. Without this, you can't make multiple proxies listen on the same IP, because they'll conflict and you won't join the right server.

^ this is a pretty non-trivial change but I'll see what I can do.

**Comment by jhead** [comment]
@edgararroyo can you try the version attached here?

[phantom-19-2019-09-15.zip](https://github.com/jhead/phantom/files/3614100/phantom-19-2019-09-15.zip)

I modified `-bind` to only take an *address* not a port -- the port will be randomized. It will automatically bind to 0.0.0.0:19132 to listen for pings and pass them through, then respond to the client using the `-bind` address. I tested it on macOS with Minecraft for iOS and successfully got two instances working:

```bash
$ ./bin/phantom-macos -server lax.mcbr.cubed.host:19132
$ ./bin/phantom-macos -server chi.mcbr.cubed.host:19132
```

^ both servers showed up within a couple seconds on iOS and I was able to join without issue.

I also tested with multiple local IPs:

```bash
$ ./bin/phantom-macos -server lax.mcbr.cubed.host:19132 -bind 192.168.1.84
# sudo ifconfig en0 alias 192.168.1.184/24 up
$ ./bin/phantom-macos -server chi.mcbr.cubed.host:19132 -bind 192.168.1.184
```

lmk if you run into any issues. If not, I can publish a new version.

**Comment by edgararroyo** [comment]
Hi, it's not same IP, it's multiple IP, that's why I was trying to use -bind

On Sep 15, 2019 12:44 PM, Justin Head <notifications@github.com> wrote:

Hey Edgar,

I think I found the issue. -bind doesn't seem to work properly because the ping packets that are sent to every device on the network have a destination of x.x.x.255 (the broadcast address), and these don't seem to be forwarded to the IP used with -bind. Without -bind, the proxy listens on all addresses, which allows it to receive those ping packets.

Docker is likely different and forwards the broadcast packets down to the containers, since you're passing --net=eth0 through -- that's probably why it works.

One solution would be for phantom to listen on 0.0.0.0:19132 (i.e. without -bind) with SO_REUSEADDR and listen on a separate IP/port. When it receives the broadcast ping packet, it triggers the second listener to respond from its own IP/port, so that the Bedrock/PE device knows what IP/port to talk to. Without this, you can't make multiple proxies listen on the same IP, because they'll conflict and you won't join the right server.

^ this is a pretty non-trivial change but I'll see what I can do.

**Comment by jhead** [comment]
Yep, understood, but it's slightly more complicated than just that. The proxy _always_ has to listen on 0.0.0.0:19132 regardless of `-bind` in order for it to show up on LAN. The version attached above is updated so that you **don't need** `-bind` to run multiple anymore, regardless of what IP you're trying to use. I've tested it with multiple instances on multiple IPs and the same IP using multiple instances.

**Comment by edgararroyo** [comment]
Still not working for me.  My 3 servers are on the same machine but different ports.

example:

1.2.3.4:19132
1.2.3.4:19133
1.2.3.4:19134

When I ran 3 proxies it only shows one server.

On Sep 15, 2019 2:45 PM, Justin Head <notifications@github.com> wrote:

Yep, understood, but it's slightly more complicated than just that. The proxy always has to listen on 0.0.0.0:19132 regardless of -bind in order for it to show up on LAN. The version attached above is updated so that you don't need -bind to run multiple anymore, regardless of what IP you're trying to use. I've tested it with multiple instances on multiple IPs and the same IP using multiple instances.

**Comment by jhead** [comment]
Oh, you're actually running the servers on the same machine? I would suggest that you change the one running on 1.2.3.4:19132 to another port and retry. Try 3, 4, 5 instead of 2, 3, 4.

**Comment by edgararroyo** [comment]
Ok, let me try.

**Comment by edgararroyo** [comment]
Here is creating 3 macvlans and using --bind

> INFO: 2019/09/15 15:20:40 proxy.go:81: Binding ping server to: 0.0.0.0:19132
> INFO: 2019/09/15 15:20:40 proxy.go:90: Binding proxy server to: 192.168.26.107:50380
> INFO: 2019/09/15 15:20:40 proxy.go:97: Proxy server listening!
> INFO: 2019/09/15 15:20:40 proxy.go:244: Starting idle connection handler
> INFO: 2019/09/15 15:20:40 proxy.go:81: Binding ping server to: 0.0.0.0:19132
> INFO: 2019/09/15 15:20:40 proxy.go:90: Binding proxy server to: 192.168.26.108:59028
> INFO: 2019/09/15 15:20:40 proxy.go:97: Proxy server listening!
> INFO: 2019/09/15 15:20:40 proxy.go:244: Starting idle connection handler
> INFO: 2019/09/15 15:20:40 proxy.go:81: Binding ping server to: 0.0.0.0:19132
> INFO: 2019/09/15 15:20:40 proxy.go:90: Binding proxy server to: 192.168.26.109:63914
> INFO: 2019/09/15 15:20:40 proxy.go:97: Proxy server listening!
> INFO: 2019/09/15 15:20:40 proxy.go:244: Starting idle connection handler
>

**Comment by jhead** [comment]
and what IP/ports are you running the Bedrock servers on?

**Comment by edgararroyo** [comment]
I will email you the IPs.  Ports 19133 thru 19135

On Sep 15, 2019 3:25 PM, Justin Head <notifications@github.com> wrote:

and what IP/ports are you running the Bedrock servers on?

**Comment by edgararroyo** [comment]
Ok, it works!  👍
