### ISSUE TITLE
Add Windows service ability

### ISSUE THREAD

**Issue by counterfitninja** [jhead/phantom#2]
Can this be updated to run as a services rather than a console app.

**Comment by counterfitninja** [comment]
Also add the ability to have multiple servers within the config ( if possible)

**Comment by counterfitninja** [comment]
I managed to create the service through nssm which works fine. Could easily support multiple servers.

**Comment by jhead** [comment]
Nice! Would you be willing to leave a comment with your steps for my own reference? @counterfitninja

**Comment by counterfitninja** [comment]
To achieve this download a copy of https://nssm.cc/download and run a command prompt from the downloaded file. then run nssm install <servicename> in my case i user nssm install phantom. This loads the parameters screen. Fill in the service.exe screen with the Phantom.exe and then put the <server>:<port> in the argument and click ok. This will create a server for you that will persist when your machine restarts.
