### ISSUE TITLE
Unable to Connect to World

### ISSUE THREAD

**Issue by mattlathrop** [jhead/phantom#24]
I'm having issues using this and would love some help!

No matter what I do I am getting a "Unable to connect to world" error. The server does always show up on the client, but it always fails to connect after a few seconds. Is there some logs I can access to figure out what is up?

My setup:
Bedrock server running on AWS Ubuntu instance. Version 1.12.1.1
I've tried clients on Xbox One and iOS 13
I've tried running Phantom on Mac or Raspberry Pi
I've tried in two different home networks

Players on Win10 and iOS can join the server successfully when they add the server directly but not through LAN. 

Here is the print out of Phantom 
`./phantom-linux-arm7 -server minecraft.xxx.com:19132
Starting up with remote server IP: minecraft.xxx.com:19132
INFO: 2019/09/27 05:47:39 proxy.go:81: Binding ping server to: 0.0.0.0:19132
INFO: 2019/09/27 05:47:39 proxy.go:90: Binding proxy server to: 0.0.0.0:50878
INFO: 2019/09/27 05:47:39 proxy.go:97: Proxy server listening!
INFO: 2019/09/27 05:47:39 proxy.go:244: Starting idle connection handler
INFO: 2019/09/27 05:47:40 proxy.go:201: Opening connection to xxx.xxx.xxx.xxx:19132 for new client 192.168.1.19:53826!
INFO: 2019/09/27 05:47:40 proxy.go:216: Opening connection to xxx.xxx.xxx.xxx:19132
INFO: 2019/09/27 05:48:04 proxy.go:201: Opening connection to xxx.xxx.xxx.xxx:19132 for new client 192.168.1.19:55657!
INFO: 2019/09/27 05:48:04 proxy.go:216: Opening connection to xxx.xxx.xxx.xxx:19132
INFO: 2019/09/27 05:48:59 proxy.go:251: Cleaning up idle connection: 192.168.1.19:53826
read udp 192.168.1.10:57358->xxx.xxx.xxx.xxx:19132: use of closed network connection
`

Would love any help you could offer!

**Comment by mattlathrop** [comment]
I also tried joining a public server like this one to no avail https://www.reddit.com/r/MCPE/comments/cedsxp/public_survival_bedrock_server/

**Comment by dub24** [comment]
The other thread about being unable to connect to a server outlined this a bit.  There appears to be an issue with Bedrock working through the proxy right now.

**Comment by jhead** [comment]
Hey @mattlathrop, thanks the report. Like dub said, this is probably related to #20 or #16 regarding compat with non-PocketMine servers. I've been out of town but I'll see if I can sort it out soon.

**Comment by jhead** [comment]
Hey @mattlathrop, could you please try [version 0.2.1](https://github.com/jhead/phantom/releases/tag/v0.2.1) and see if this problem is resolved?

**Comment by mattlathrop** [comment]
I tested with a Mac OS computer as the phantom computer and an Xbox and an iOS device as the client and it worked perfectly. I’ll try to test some more device combinations in the coming days!
