### ISSUE TITLE
i can't get permissions

### ISSUE THREAD

**Issue by ProdigyGG** [jhead/phantom#25]
I'm on macOS and on terminal. whenever i put the "phantommacos.dms" thing into terminal and i press enter. it says permissions denied.

**Comment by ProdigyGG** [comment]
![Image 10-1-19 at 3 59 PM](https://user-images.githubusercontent.com/55936411/65995965-7dcd9b80-e464-11e9-8946-50798e4e3df5.jpg)

**Comment by jhead** [comment]
Hey @ProdigyGG, please double check the [readme](https://github.com/jhead/phantom/blob/master/README.md). For macOS, you'll want to download the `phantom-macos` file and then:

1. Open Terminal
2. Navigate to wherever you downloaded phantom, ex. `cd Downloads`
3. `chmod +x phantom-macos`
4. `./phantom-macos -server <server-ip>`

Let me know if you run into any other issues.

**Comment by ProdigyGG** [comment]
<img width="577" alt="Screen Shot 2019-10-08 at 6 22 06 PM" src="https://user-images.githubusercontent.com/55936411/66437748-a0c5f580-e9f8-11e9-8ad7-e1e718614ee8.png">

**Comment by jhead** [comment]
Hey @ProdigyGG, you'll need to modify the `cd` command to change to the folder where you downloaded the file if it's not under `Downloads`. ex: if it's on your desktop instead, `cd Desktop`

**Comment by ProdigyGG** [comment]
Yes my phantom macOS is in my downloads, but it is still not working
![Screen Shot 2020-02-11 at 5 52 40 PM](https://user-images.githubusercontent.com/55936411/74287236-77470e80-4cf7-11ea-88e2-ee1eab6e2f31.png)
