### ISSUE TITLE
Doesnt work for 32 bit pc

### ISSUE THREAD

**Issue by KYH2007** [jhead/phantom#26]
Can you make it work on a 32 BIT PC

**Comment by jhead** [comment]
Hey @KYH2007, what OS are you using?

**Comment by KYH2007** [comment]
i am on windows 10 on a 32 bit device
________________________________

**Comment by jhead** [comment]
Hey @KYH2007, I've added a 32-bit version for Windows. Could you try that out?

https://github.com/jhead/phantom/releases/download/v0.2.1/phantom-windows-32bit.exe
