### ISSUE TITLE
Version 0.2.0 not working on windows host

### ISSUE THREAD

**Issue by dorianxonic** [jhead/phantom#27]
I do not own an XBOX, this was the result of guiding a friend through the process.
v0.2.0:
```
Reads the number of maximum players correctly.
Throws an "unable to connect" message when trying to use it.
```
v0.1.0:
```
Reads an incorrect number of maximum players.
Connects flawlessly.
```

**Comment by jhead** [comment]
Hey @dorianxonic, thanks for the report. This is already being tracked in #20 

https://github.com/jhead/phantom/issues/20#issuecomment-534415209

**Comment by jhead** [comment]
Hey @dorianxonic, could you please try [version 0.2.1](https://github.com/jhead/phantom/releases/tag/v0.2.1) and see if this problem is resolved?

**Comment by dorianxonic** [comment]
Version 0.2.1 doesn't work on linux host anymore with a local Minecraft for Windows 10 running.
I can only test on MCPELauncher for now, but 0.1.0 works flawlessly on both Linux and Widows  hosts.
Will edit this and report trying 0.2.1. from a windows 7 machine in a bit.

**Comment by dorianxonic** [comment]
Update:
Both Windows (x64) and Linux (non-arm) work perfectly fine. My issue was I had a server instance saved and the LAN party would not appear for whatever reason. Once I deleted the instance, phantom did make the server show up perfectly fine. Sorry for bothering, it's all good. I could test on a raspberry Pi whenever I have some time. I will ask someone with an XBOX to test it out too but in W10 and Android clients it does work flawlessly although it's pointless to use it for them.
