### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bombman5963** [jhead/phantom#28]
i typed 
$ ./phantom-windows 104.219.6.162:19132
to test it and it told me the following
I am currently running windows 10 , 64 bit with 4 gb of ram

![Capture1](https://user-images.githubusercontent.com/38389066/66871228-38839080-ef71-11e9-89c0-4ee49be1ea14.PNG)

**Comment by bombman5963** [comment]
@jhead

**Comment by bombman5963** [comment]
@jhead

**Comment by jhead** [comment]
Hey @bombman5963, remove the $ from the beginning of the command, and make sure the command ("phantom-windows") matches the file you've downloaded.

You can download the windows exe file from the Releases page on GitHub, or here: https://github.com/jhead/phantom/releases/download/v0.2.0/phantom.exe

In that case, the command should be: `./phantom.exe -server 104.219.6.162:19132`

Let me know if you get any other errors.

**Comment by bombman5963** [comment]
@jhead i ran the .exe file you sent and my firewall blocked it. i clicked run anyways and then my pc made a beeping noise 3x and then my antivirus said it was dangerous

**Comment by jhead** [comment]
Hey @bombman5963, not sure what to tell you. This is an open source project so your anti-virus is probably a little oversensitive. Here's a virus scan report:

https://www.virustotal.com/gui/url/c9e9852d137dc50b04e3d125d8fd2783babd7b8c951729026320f7ca98861753/detection
