### ISSUE TITLE
Only working on port 19132

### ISSUE THREAD

**Issue by counterfitninja** [jhead/phantom#29]
I have 2 server running on the same remote server but on different ports. It seems that Phantom only works on port 19132. If i use port 19134 it does not show up.

**Comment by jhead** [comment]
Hey @counterfitninja, you don't actually need to use a different port. phantom will automatically select a port and tie the LAN entry on the server list to that port. Using a different port in phantom will cause it to not show up on the LAN list.

Example below, I tested with two servers and was able to connect to both:

<img width="1516" alt="Screen Shot 2019-10-26 at 10 28 21 AM" src="https://user-images.githubusercontent.com/360153/67623552-7e472100-f7db-11e9-9ab8-f1383eb080a0.png">

![IMG_6950](https://user-images.githubusercontent.com/360153/67623573-c49c8000-f7db-11e9-8c33-c190ae995a58.png)

**Comment by counterfitninja** [comment]
I'm not trying to use different ports on phantom. 
I have two bedrock servers running on the same  azure vm server  but they run off different port to allow 2 server to run off the one server. I then want phantom to run locally so they both show up.

**Comment by jhead** [comment]
Hmm, I'm not seeing the issue when trying the same setup. I've got two remote servers configured on different ports 19132 and 19134.

<img width="1652" alt="Screen Shot 2019-10-26 at 10 45 19 AM" src="https://user-images.githubusercontent.com/360153/67623749-c2d3bc00-f7dd-11e9-82eb-cbcbcdfee438.png">

![IMG_6951](https://user-images.githubusercontent.com/360153/67623812-7fc61880-f7de-11e9-8629-933179e3f4a2.png)

The only difference compared to yours is probably that they're different IPs. I tried it with two Docker containers running Bedrock on the same PC on different ports and got the same result -- both show up on iOS and I can connect.

**Comment by counterfitninja** [comment]
Ill do a little more testing with my RPi but at the moment Phantom is not showing up on my xbox at all at the moment, so until i sort that, i cant do much testing.

**Comment by counterfitninja** [comment]
So i have been doing a lot of testing to try and determine what is going on and why im seeing different results than you.  All this has been tested on my win2019 server and raspberry Pi, both to my own server and the two servers you highlight above. 

Test 1)   Using the 0.1.0 release of Phantom both server on port 19132  show up in Minecraft ( On Win10 and Android) 

Test 2)   Using the 0.1.0 release of Phantom both server on port 19134  show up in Minecraft ( On Win10 and Android) 

Test 3) using Release 0.2.1 and phantom running a single session of phantom connecting to my server on port 19132 show up in Android and NOT on Win10 Minecraft

Test 4) using Release 0.2.1 and phantom running a single session of phantom connecting to Cubed.host on port 19132 shows up on Android and Windows without issue. 

Test 5) using Release 0.2.1 and phantom running a single session of phantom connecting to my server on port 19134 does not show up on either device

Test 6) using Release 0.2.1 and phantom running a single session of phantom connecting to cubed host on port 19134 does not show up on either device. 

Im not quite sure what conclusions to draw here. The newer code is stopping something for me on ports that are not 19134 but it also seems like my own server is doing something slightly different than Cubed.host. The main difference i can see is that im running the offical 1.3.0 Bedrock Server and Cubed are running pocketmine.

**Comment by counterfitninja** [comment]
Hey All, I think this can now be closed. After the release of v4 i started to a lot more digging. It seemed that new created servers were working fine. So i did a lot of digging and this morning i noticed an NBT tag within the level called LANBroadcast which was set to0.  I have to assume this got set through some testing on a local machine. However setting LANBroadcast to 1  thkough MCCtoolchest enabled Phantom to broadcast my network properly. really happy this is now working as expected. Great work. Can i donate to the project anywhere?

**Comment by jhead** [comment]
Hey @counterfitninja, glad you got it working! That's a pretty strange solution. This server that you had trouble with -- it was remote, right? It wasn't on your LAN?

**Comment by counterfitninja** [comment]
Yeah all my servers are on Microsoft Azure. The old version of phantom used to work but not newer ones. So when you released 4 I decided to take a deep dive at what was up considering new servers seems to be fine. This one certainly took some hunting but thought I needed to document my findings in case others have the same thing.

**Comment by imnotjack91** [comment]
@counterfitninja  i too am attempting to leverage azure but not quite to do the hosting, i have some questions about azure that i have been struggling to make happen. when you have a chance can we talk?

**Comment by counterfitninja** [comment]
I have just stuck my email on my profile. Drop me a line and ill see if i can help

**Comment by imnotjack91** [comment]
just emailed you. feel  free to remove it again

**Comment by Arnesh148** [comment]
Hello can anybody help me i am new i dont know how it works

**Comment by pauljsymonds** [comment]
How do we get this working on latest Bedrock PS5?
