### ISSUE TITLE
Feature Requests + Word of thanks :)

### ISSUE THREAD

**Issue by 7kasper** [jhead/phantom#3]
Hey I've been looking to create something similar to this, but didn't come around to it yet.
Simple tool, works good and is exactly what some have been looking for. Thanks alot!

So I don't think this should get very much more complicated. A few things to add in the future would be:
- [x] DNS support. (#1)
- [ ] A simple GUI (Idk if any gui is simple in GO, but I can imagine quite a few users would be discouraged by CLI)
- [ ] Android support. (Host the proxy on your phone, since everybody has one)

**Comment by Mhowser** [comment]
qt might be good for the GUI

**Comment by Mhowser** [comment]
Hosting the proxy on a smartphone would likely yield poor results due to being limited to a wireless connection, and low processing power.

**Comment by edgararroyo** [comment]
I agree with #3, Android support.  There are Android phones out there with enough power and 802.11n or 802.11ac that should be good enough to do this, and would be VERY useful.

**Comment by jhead** [comment]
Thanks for the support. I've opened a couple issues for the suggestions and will track progress there if/when I can get around to it. No promises :)

#21 mobile apps
#22 UI
