### ISSUE TITLE
I must be stupid

### ISSUE THREAD

**Issue by Gtruen** [jhead/phantom#33]
So forgive me as I am not a command prompt master like most of you are but how do I enter the correct ip address for my server?  My son is wanting me to set up a server for him and I have spent like 2 hours try to get this to work.  I have dragged and dropped it into the command prompt and hit enter but it doesn't let me edit the ip.

**Comment by firstdriverlesscar** [comment]
You need to add the server IP address after the command. I am temporarily running this on a Mac so my  command in terminal looks like:

`$ /users/my_username/Downloads/phantom-mac-os -server xxx.xxx.xxx.xxx:19132`

**Comment by jhead** [comment]
Hey @Gtruen! The easiest way is to open Command Prompt from your start menu if you're on Windows, or open Terminal from your apps on macOS. Once open, you can type the full path to the version of phantom you downloaded, along with any options after it.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/360153/69667074-2a319580-1042-11ea-9c26-848920433a60.png">

As shown, you can also use the `cd` command to navigate to the correct folder where you saved phantom to.
