### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by trixxyz** [jhead/phantom#36]
Hi this isn't an issue but more of a request I was wondering if it was possible for you guys to make a video on how to set up phantom I'm not sure how to use it. Sorry for sounding like this I'm just super lost as all of this is new to me, I tried to read the usage section but am still super lost

**Comment by ProdigyGG** [comment]
There are many videos like dakonblackrose’s video

**Comment by jhead** [comment]
Hey @trixxyz, there are lots of YouTube videos out there if you still need some help.

https://www.youtube.com/watch?v=S8Fo7uyHr_M
https://www.youtube.com/watch?v=MHLG8TQqRBw

Some might be a little outdated so make sure you read the instructions on the main phantom page 🙂
