### ISSUE TITLE
This app can't run on your PC.

### ISSUE THREAD

**Issue by trixxyz** [jhead/phantom#37]
Hi, so I'm trying to use phantom to make my server show up as a lan so people watching my stream can connect to it, but when I try to do it I get this error.
https://imgur.com/a/tIwBWkP

**Comment by jhead** [comment]
Hey @trixxyz, a bit late but make sure you're using the correct 32-bit or 64-bit version for your PC. If you check the latest version on the Releases page [here](https://github.com/jhead/phantom/releases/tag/v0.2.1), you'll find both 32/64-bit downloads available.
