### ISSUE TITLE
Needing to restart program

### ISSUE THREAD

**Issue by RHThree** [jhead/phantom#44]
My friends and I are trying to use phantom so we can play on a server, but he gets disconnected after a while and has to reenter the command. Any solution or am I missing something? Or is it just a bug?

**Comment by d5c4b3** [comment]
I've been having this issue while using phantom. It seems to happen more often when both my SO and myself are connected to the same phantom server. It happens at random intervals.

**Comment by d5c4b3** [comment]
Attached log file from crash

[2019-12-31_21-59-15.txt](https://github.com/jhead/phantom/files/4013587/2019-12-31_21-59-15.txt)

**Comment by jhead** [comment]
Thanks for the logs @d5c4b3! Definitely looks like a bug. I’ll see what I can find.

**Comment by d5c4b3** [comment]
I think it's just concurrent read/write of the idleMap. [I forked and added a mutex](https://github.com/d5c4b3/phantom/tree/44-mutex). It's a very naive lock and might cause issues if idleMap gets big. It might be possible to use sync.RWLock instead. We might also try sync.Map.

I might also be missing an obvious fix. I'm very new to Go.
