### ISSUE TITLE
Change display name from remote server 

### ISSUE THREAD

**Issue by counterfitninja** [jhead/phantom#5]
Is it possible to change the display name from Remote Server to a customer name. I have a couple of services running and remembering the difference is tricky,

**Comment by jhead** [comment]
Thanks for the suggestion! I'll look into it.

**Comment by jumuro-dev** [comment]
It would also be nice to be able to change the version of the server and the number of users.

**Comment by jhead** [comment]
I ended up making the server's display name pass through. So it's not customizable yet but it corresponds to the remote server.
