### ISSUE TITLE
Getting kicked after a very short period of time.

### ISSUE THREAD

**Issue by d5c4b3** [jhead/phantom#52]
Phantom is cleaning up an idle connection that is not idle causing me to get kicked shortly after joining ~40 seconds.

This is the newest version after the ClientMap update.

**Comment by jhead** [comment]
lol thanks. If you're curious, I was updating `clientEntry.lastActive = time.Now()` but the map was `map[string]clientEntry` and not `map[string]*clientEntry`, so it wasn't mutating the underlying object.
