### ISSUE TITLE
Connect to a Nukkit server whith a PS4

### ISSUE THREAD

**Issue by djmichaelsaler** [jhead/phantom#55]
I am trying to connect to a server that I want to mount with plugins using PS4. The server is Nukkit type, the map cannot be downloaded and disconnected. Not even the message that a player wants to connect appears on the server console. The Nukiit server is for version 1.14
https://nukkitx.com

**Comment by jhead** [comment]
Hey @djmichaelsaler, looks like this is a duplicate of #16. Nukkit isn't supported at the moment, though it's not intentional. I'm still looking into how we can add support for Nukkit but no news yet. Sorry about the hassle.
