### ISSUE TITLE
Problem using program

### ISSUE THREAD

**Issue by joyfulnobody** [jhead/phantom#58]
Whenever I try to use it, it doesn't work. I drag the EXE file into a cmd, add a space and paste the server info but nothing happens. Am I doing something wrong?

**Comment by ProdigyGG** [comment]
Do not add a space

**Comment by jhead** [comment]
Hey @joyfulnobody, could you provide a screenshot of the command you're using? It sounds like you might be leaving off the `-server` argument. For example, it might look like: `./phantom-windows.exe -server lax.mcbr.cubed.host:19132`

**Comment by jhead** [comment]
Closing this but feel free to reply if you need any more help.
