### ISSUE TITLE
Was running great until Bedrock 1.14.32.1

### ISSUE THREAD

**Issue by xrstokes** [jhead/phantom#59]
I've been using version 0.3.1 for months no issue. Huge thankyou by the way. But since the most recent update [3days ago]. It just stopped working. I've tried heaps of thing but it's no good for me. The funny thing is. That phantom shows a new connection from my xbox one. but it never shows up in the friends list on the xbox itself. :(

**Comment by counterfitninja** [comment]
Can also confirm this the same. I was having differing connection issues but as of the latest Bedrock update, nothing shows up on the console but im seeing connections to phantom

**Comment by ProdigyGG** [comment]
If it doesnt show up on your list. Use this method https://youtu.be/0B5T3btxFy0. It doesnt show up because your server config is iPv4. The method i listed only works for iPv4 users.

**Comment by counterfitninja** [comment]
I'm not quite sure what that video is explain, but I think it's dns redirection. https://github.com/valknight/MCBedrockDNSGuide some thing similar to this. I'll experiment in the shirt term from this guide. Also not sure what you mean by ipv4

**Comment by JDCain** [comment]
I'm having no issues with the Linux version. I was able to setup a local redirect to a Azure instance of the server,

**Comment by counterfitninja** [comment]
I'll try it on a linux server, but I have no luck on win10 win2019 svr or a raspberry pi. M

**Comment by counterfitninja** [comment]
Set up a ubuntu machine on the local network, and the log says it connecting to a client, but nothing is showing up in Minecraft. Do i need to open any ports on Linux? ( Im not a linux guys so may need some pointers)

**Comment by xrstokes** [comment]
I know I'm the one that raised this and I apologise but now it is working. I can't been sure what fixed it but I think it was firewall related. My friends and I can all play together now. Thanks again to the author.

**Comment by JDCain** [comment]
Are any parts of your network on different subnets? My understanding is that UDP broadcast won't cross to a different subnets. So if you have a guest network you won't see the advertisement on that network even if it can connect to things on the internal.

**Comment by xrstokes** [comment]
I have a complicated set up at home as any nerd does. I have the minecraft server on an "orange" DMZ network, and my xbox is connected to my "green" home network. My friends can access the Minecraft server through a port forward using your software at their house. Using your software on the green network at home I can access it across the network as well. Is there a way I can donate?

**Comment by counterfitninja** [comment]
I'm seeing mixed result.  Setup a linux vm and that was showing up on xbox around lunch, then sat down later to play on xbox and would not show up. No changes to network or vm in that time. Phantom respond that it could see the xbox but xbox would not show up. Might try the 1.16 beta in case that works.

**Comment by jhead** [comment]
Hey @counterfitninja, any luck? I tested 1.14.32.1 and didn't have any issues getting it to work with phantom.

**Comment by counterfitninja** [comment]
Thought it was my network. Had a hub sections that I thought the packets were being blocked so move my pi to the same network as the xbox. V1.1 shows up instantly but 0.3.1 doesn't. Cannot work it out. The Ubuntu version showed up for a day and not seen it again. Its really odd. Had wires hark running to try and figure it out but nothing. Can you add A logging toggle for verbose logging?

**Comment by BRadHoc** [comment]
Having the same issue here, I had an earlier build of the bedrock dedicated server installed, installed phantom and it connected, updated the server to 1.14.32.1 and now phantom won't work anymore.

**Comment by jhead** [comment]
Hey all, apologies for the delay. Could you try the latest phantom version v0.4.0?
https://github.com/jhead/phantom/releases

**Comment by counterfitninja** [comment]
No problem with the delay. Im downloading now and will follow up with some feedback after testing.

**Comment by counterfitninja** [comment]
Ok so initial testing still not showing up on my lan tab. Do you want me to attach the debug output to one of these comments? If you need me to do any more testing outside of github give me a shout directly and im happy to help out. . Out of interest what server version are you using? Windows or Linux? im only running Windows atm so wondered if that may be it. My server is running our of Azure so easy enough to create a linux version for testing.

**Comment by counterfitninja** [comment]
Some more testing. i have installed a new Ubuntu and Windows 2019 server, and so far, finger corssed they are both performing as i would expect. I will look at my old sever and try and find out what they issue there is, but on the surface all seems to be working well.. Great work.

**Comment by jhead** [comment]
Gonna close this one since the OP got past their issue.
