### ISSUE TITLE
Stuck on 'Starting Ping Handler'

### ISSUE THREAD

**Issue by Benji-Collins** [jhead/phantom#6]
When I try to start phantom I get this:

`C:\Users\colli\Downloads>phantom 139.99.197.26:19132`
`Starting up with remote server IP: 139.99.197.26:19132`
`INFO: 2019/03/13 17:43:02 proxy.go:60: Binding proxy server to: 0.0.0.0:19132`
`INFO: 2019/03/13 17:43:02 proxy.go:71: Proxy server listening!`
`INFO: 2019/03/13 17:43:02 proxy.go:209: Starting idle connection handler`
`INFO: 2019/03/13 17:43:02 proxy.go:192: Starting ping handler`

It then just stays there. Any ideas?

**Comment by CubedHost-Internal** [comment]
:wave: 

Are you experiencing any issues with connecting to the server locally? That's expected output, as long as the `Proxy server listening!` message shows up. 
Example output once a user opens up Minecraft on a phone:
```
[subtato@arch ~]$ ~/Downloads/phantom-linux sea.demo.mymc.io:19132
Starting up with remote server IP: sea.demo.mymc.io:19132
INFO: 2019/03/13 16:44:55 proxy.go:60: Binding proxy server to: 0.0.0.0:19132
INFO: 2019/03/13 16:44:55 proxy.go:71: Proxy server listening!
INFO: 2019/03/13 16:44:55 proxy.go:209: Starting idle connection handler
INFO: 2019/03/13 16:44:55 proxy.go:192: Starting ping handler
INFO: 2019/03/13 16:45:27 proxy.go:199: Ping from 10.51.0.44:44816!
INFO: 2019/03/13 16:45:28 proxy.go:199: Ping from 10.51.0.44:44816!
INFO: 2019/03/13 16:45:30 proxy.go:199: Ping from 10.51.0.44:44816!
...
```

**Comment by Benji-Collins** [comment]
I realised that you need Minecraft on Xbox open before it goes any further. I had only been trying with the windows 10 edition.

**Comment by subtato** [comment]
I see you've already closed/likely saw the response I had sent on the wrong account (oops!) or found it out on your own. For others, please see the below information.

:wave: 

Are you experiencing any issues with connecting to the server locally? That's expected output, as long as the `Proxy server listening!` message shows up. 

Example output once a user opens up Minecraft on a phone:
```[subtato@arch ~]$ ~/Downloads/phantom-linux sea.demo.mymc.io:19132
Starting up with remote server IP: sea.demo.mymc.io:19132
INFO: 2019/03/13 16:44:55 proxy.go:60: Binding proxy server to: 0.0.0.0:19132
INFO: 2019/03/13 16:44:55 proxy.go:71: Proxy server listening!
INFO: 2019/03/13 16:44:55 proxy.go:209: Starting idle connection handler
INFO: 2019/03/13 16:44:55 proxy.go:192: Starting ping handler
INFO: 2019/03/13 16:45:27 proxy.go:199: Ping from 10.51.0.44:44816!
INFO: 2019/03/13 16:45:28 proxy.go:199: Ping from 10.51.0.44:44816!
INFO: 2019/03/13 16:45:30 proxy.go:199: Ping from 10.51.0.44:44816!
...```

Essentially, the server should be running fine, you just need to open your Minecraft client and hop on the server! :smile:
