### ISSUE TITLE
cannot join with xbox with server in ONLINE mode. 

### ISSUE THREAD

**Issue by imnotjack91** [jhead/phantom#64]
laptop over wifi hosting the proxy works fine. 
its something to do with my desktop (on Ethernet)

when the desktop is hosting:
primary is fine but the secondary server cannot be joined but both can be seen while the servers are running in offline mode. this goes cross platform to at least android and ios as well as xbox

when the servers are running in online mode, they can still be seen but both error out with 
"You need to authenticate to Microsoft Services" from xbox. 
ios and android run perfectly fine from desktop in online mode.

Both computers are on the same router on the same IP table

the only difference is the desktop also has a physical vpn crossover cable for server management to the server itself using its own dedicated network card. I've ruled this out as an issue by disabling that NIC but the issue doesnt change
they both use the same version of windows 10, 
same account
same licensing
same software versions
same firewall rules
same network path to the server
same network aside from physical connection properties

**Comment by counterfitninja** [comment]
Can you define offline mode? Its seems like a similar problem to the one i have with the server not showing up all the time,

**Comment by imnotjack91** [comment]
this setting is found in the server.properties file

online-mode=false
# If true then all connected players must be authenticated to Xbox Live.
# Clients connecting to remote (non-LAN) servers will always require Xbox Live authentication regardless of this setting.
# If the server accepts connections from the Internet, then it's highly recommended to enable online-mode.
# Allowed values: "true" or "false"

**Comment by imnotjack91** [comment]
wow that pasted weird let me try that again.
online-mode=false
# If true then all connected players must be authenticated to Xbox Live.
# Clients connecting to remote (non-LAN) servers will always require Xbox Live authentication regardless of this setting.
# If the server accepts connections from the Internet, then it's highly recommended to enable online-mode.
# Allowed values: "true" or "false"

**Comment by counterfitninja** [comment]
Ah you mean on the bedrock server side. Interesting. I'll look late tonight.

**Comment by imnotjack91** [comment]
`online-mode=false
# If true then all connected players must be authenticated to Xbox Live.
# Clients connecting to remote (non-LAN) servers will always require Xbox Live authentication regardless of this setting.
# If the server accepts connections from the Internet, then it's highly recommended to enable online-mode.
# Allowed values: "true" or "false"
`

**Comment by imnotjack91** [comment]
lol dang it. it wont paste correctly

**Comment by imnotjack91** [comment]
im updating the original post with more info

**Comment by imnotjack91** [comment]
lol..... nvm.... sign out and sign in on xbox fixed the issue. creds got stuck i guess.
