### ISSUE TITLE
YouTube Tutorial for Phantom

### ISSUE THREAD

**Issue by mtoensing** [jhead/phantom#65]
Hi, 

here is a YouTube Tutorial. You could embed it into the github readme.md if you like. This could help people a lot.

https://youtu.be/UEfqpKyDQ48

**Comment by Bullet55NL** [comment]
> Hi,
> 
> here is a YouTube Tutorial. You could embed it into the github readme.md if you like. This could help people a lot.
> 
> https://youtu.be/UEfqpKyDQ48

This helped me. Thanks.

**Comment by Rozkalns** [comment]
Well, I skipped all the raspberry part, but maybe - thats the issue... But, not sure.

I ran this
`./phantom-macos --server xx.xx.xx.xx:19132`

And on my Xbox I can see Friends [1], but Jointable friends - none.
![IMG_8168](https://user-images.githubusercontent.com/8157701/81225015-3d815d80-8ff1-11ea-819c-00fa3e4a52f4.jpg)

Any help about this issue?

**Comment by Bullet55NL** [comment]
I noticed you used 2 dashes before ''server'' in your code.

> ./phantom-macos **--server** xx.xx.xx.xx:19132

The proper command would be:

>  ./phantom-macos -server xx.xx.xx.xx:19132

Can you screenshot the outcome of your console when entering those commands?

**Comment by Rozkalns** [comment]
<img width="964" alt="Screenshot 2020-05-07 at 10 11 27" src="https://user-images.githubusercontent.com/8157701/81265589-055b3880-904c-11ea-9383-d441e28a1ea4.png">
output is the same.
When opened minecraft on Xbox, got INF debug spamming, as usual.

PS, I was able to connect from my iPhone to this server via Friends tab.

Dunno, is this because I don't have Xbox Gold (to play live games) at the moment? Well, I believe, that this way I would be able to coonect via Servers tab.

**Comment by Bullet55NL** [comment]
Well technically you are connecting to a LAN server, so you shouldn't have Xbox Gold to play. 
When i log in on my Iphone & PS4 i see a LAN feature pop-up.

Is your Xbox connected to the same network as the Macbook?

**Comment by Rozkalns** [comment]
Yes, the same only network I have at home. 
I think that something fishy is happening on Xbox side, because I can clearly see Friends [1] come and go as I start and stop the proxy on my Mac. I think they filtered this out. Maybe there is a workaround.

**Comment by counterfitninja** [comment]
Have you opened the mac firewall to allow these ports through?

**Comment by Bullet55NL** [comment]
Have you tried connecting to other servers with the console?

Try these and test if it will pop-up on Xbox.

play.hybridcounty.com:19132
play.nethergames.org:19132
ecpehub.net:19132

**Comment by Rozkalns** [comment]
@counterfitninja I don't have firewall enabled on my Mac. As always, by default is off. But still - I was able to connect to proxy via iOS device.

@Bullet55NL Oh thanks, good idea to try different servers :) Definetly will check this out! I feel like my server.properties on my pocketmine server is incorrect maybe. Do you have example, maybe, of your config. Keep in mind to remove rcon password :)

**Comment by Rozkalns** [comment]
As well as, I checked that if I start a game on my iPhone, I can see Friends[1], if I start proxy - I see Friends[2]. 
Definetly, something is wrong with Minecraft on Xbox. Maybe reinstalling might help.

**Comment by counterfitninja** [comment]
Have you turned the firewall off specifically? They are on by default and should not really be turned off

**Comment by Rozkalns** [comment]
Firewall is off
![image](https://user-images.githubusercontent.com/8157701/81276929-5a06af80-905c-11ea-9713-61e43cb350c0.png)

**Comment by Bullet55NL** [comment]
Are you hosting your own server? Or are you renting a server? What version type is your server?
I'm sure the server will pop-up if your're running (or renting) a bedrock server on version 1.14.60

**Comment by counterfitninja** [comment]
I'm running my own dedicated server from the Minecraft site.

**Comment by Bullet55NL** [comment]
Realms ?

**Comment by counterfitninja** [comment]
No not realms. You can down load an official server for bedrock from the Minecraft site. Search for bedrock dedicated server

**Comment by Bullet55NL** [comment]
What server version pops-up when you try and connect with your Iphone

**Comment by counterfitninja** [comment]
It's 1.14.60. That's the latest server version.

**Comment by Bullet55NL** [comment]
Is LAN broadcast in your server settings turned on? 

![5C5EE02D-159E-4EE4-901D-FF92B1585C51](https://user-images.githubusercontent.com/42201487/81394390-25f5c200-9122-11ea-83ba-a24eea96c83b.png)
![A5F302F0-DFDC-484B-A607-D181C2E237E6](https://user-images.githubusercontent.com/42201487/81394395-28f0b280-9122-11ea-9a03-2c42f1e3dd37.png)
