### ISSUE TITLE
Phantom 1.1 32 bits ?

### ISSUE THREAD

**Issue by Maeam77** [jhead/phantom#68]
Hello, i want to play minecraft server on my PS4 but i have a pc with 32 bits, can you give me a version of 0.1.1 32bits please

**Comment by jhead** [comment]
Hey @Maeam77! There's a 32-bit version of all the recent versions of phantom on the [Releases](https://github.com/jhead/phantom/releases) page. Older versions, especially 0.1.1 are not supported. If you're running into an issue with a newer version, please open an issue so I can look into it 🙂
