### ISSUE TITLE
MacOS can't use Pro servers.

### ISSUE THREAD

**Issue by ShepherdTamer** [jhead/phantom#7]
Hi, so I am currently trying too join a pro server but this keeps coming up saying unable too join, but when I join a basic server it connects fine.

**Comment by jhead** [comment]
Hey @ShepherdTamer! I'm not sure I understand your request. Could you provide any more info?

**Comment by ShepherdTamer** [comment]
So I am on a server provided by server.pro which is their highest priced one, but too allow the connection I have too first log into the server via PE or w10 and then phantom connects

Kind Regards

Kai Shepherd

**Comment by jhead** [comment]
Sorry about that, I'm not familiar with server.pro. I've only tested this against local and [CubedHost](cubedhost.com) servers, and haven't seen this issue before. You might want to verify that the server is always online, rather than just turning on when a player joins.
