### ISSUE TITLE
un able to connect to world

### ISSUE THREAD

**Issue by goldypizza** [jhead/phantom#71]
I'm using the newest one and the minecraft server is play.primegames.net:19132 i do everything right and it works and i connect to the server and i see it on the ps4 i click on it and it says connecting to multiplayer game and then it say unable to connect to world any idea why?

**Comment by counterfitninja** [comment]
I had this recently. It was due to the latest update so my server was on and over version to the client. Can you try it from a pc using the server tab and check what versions your on

**Comment by istaducati** [comment]
Im having the same issue and all of my clients are running the same version as the server, 1.14.60

**Comment by istaducati** [comment]
it is for all of my clients

**Comment by jhead** [comment]
Closing this issue since it's been inactive for a while. If you're still having trouble with phantom, please try updating to the latest version and let me know if the issue still occurs.
