### ISSUE TITLE
chmod command on RaspberryPi

### ISSUE THREAD

**Issue by Bullet55NL** [jhead/phantom#78]
Hello,

> $ chmod u+x ./phantom-<os>

Doesn't work on a RaspberryPi when logged in as user ''pi''

Use this instead: 

> chmod a+x ./phantom-<os> 

Don't forget to replace <os> with macos, linux, etc. for the correct OS you're using.

**Comment by jhead** [comment]
Hey @Bullet55NL, not sure what the exact error was but this might be specific to your Pi setup. Using `a+x` works too, it's just more open to other users on the system.
