### ISSUE TITLE
Can't Build on i386 Linux Architecture

### ISSUE THREAD

**Issue by timnolte** [jhead/phantom#8]
I currently have an older box that I just got an Ubuntu 18.04 install going on with NukkitX Minecraft PE server. I'd like to setup this proxy i the hopes that it makes it easier for my kids to join the server. Currently, no matter what tweaks I make to the Makefile I can't get it to build on the i386 architecture. I have Go installed and make. Seems like this should build.

**Comment by jhead** [comment]
Hey @timnolte, did you try modifying the Makefile and setting `GOARCH=386` with an appropriate `GOOS`?

ref: https://golang.org/doc/install/source#environment

**Comment by timnolte** [comment]
@jhead when I try that I end up with the following failure:

```
minecraft@minecraft:~/downloads/minecraftbe-server/phantom-0.1.1$ make bin/phantom-linux
GOOS=linux GOARCH=386 go build -o bin/phantom-linux cmd/proxy.go
cmd/proxy.go:8:2: cannot find package "github.com/jhead/phantom/internal/proxy" in any of:
        /usr/lib/go-1.10/src/github.com/jhead/phantom/internal/proxy (from $GOROOT)
        /opt/minecraft/go/src/github.com/jhead/phantom/internal/proxy (from $GOPATH)
Makefile:14: recipe for target 'bin/phantom-linux' failed
make: *** [bin/phantom-linux] Error 1
```

After coping the contents of the `internal` directory to `/opt/minecraft/go/src/github.com/jhead/phantom/internal/` and trying to `make` I got the following:

```
mkdir -p bin
GOOS=linux GOARCH=386 go build -o bin/phantom-linux cmd/proxy.go
cmd/proxy.go:8:2: use of internal package not allowed
Makefile:8: recipe for target 'bin/phantom-linux' failed
make: *** [bin/phantom-linux] Error 1
```

**Comment by timnolte** [comment]
So I actually ended up doing this:

1. Copied the `cmd` directory also to `/opt/minecraft/go/src/github.com/jhead/phantom/`.
2. `cd /opt/minecraft/go/src/github.com/jhead/phantom`.
3. Executed: `go build -o ~/downloads/minecraftbe-server/phantom-0.1.1/bin/phantom-linux cmd/proxy.go`

And that actually worked and built the binary file. I tried it out but my clients failed to connect. So I'm not sure If I broke something when building it that way.

**Comment by jhead** [comment]
Hm, golang expects a very specific directory structure. Copying certainly works but you should check out the official docs: https://golang.org/doc/code.html#Workspaces

What error/message do you see when connecting? Does it show up on the list at all?

I rebuilt it for linux + i386 on my machine and attached it, lmk if it works.
[phantom-linux-i386.zip](https://github.com/jhead/phantom/files/3103723/phantom-linux-i386.zip)

**Comment by jhead** [comment]
Gonna close this one out since I was able to build it for i386 on Linux. Let me know if you aren't able to get it working.
