### ISSUE TITLE
running phantom-linux does not appear in LAN on minecraft

### ISSUE THREAD

**Issue by PrototypeXodeus** [jhead/phantom#80]
Running a dedicated minecraft bedrock server on a friend PC, attempting to use phantom-linux to allow my ps4 to connect to the dedicated server.

I can't seem to get the LAN server to show up ANYWHERE. Not on the ps4, not on my personal PC running bedrock edition.

When the phantom-linux is running in terminal, it detects when my PC IP address and the PS4 open minecraft by displaying "New Connection from client..." but when I check my LAN available worlds on either the ps4 or my PC neither show anything.
![Screenshot_20200503_213818](https://user-images.githubusercontent.com/64760223/80931419-bb423080-8d87-11ea-92aa-537c8e599ce0.png)

**Comment by Bullet55NL** [comment]
Is LAN broadcast in your server settings turned on? 

![5C5EE02D-159E-4EE4-901D-FF92B1585C51](https://user-images.githubusercontent.com/42201487/81394390-25f5c200-9122-11ea-83ba-a24eea96c83b.png)
![A5F302F0-DFDC-484B-A607-D181C2E237E6](https://user-images.githubusercontent.com/42201487/81394395-28f0b280-9122-11ea-9a03-2c42f1e3dd37.png)

**Comment by counterfitninja** [comment]
Not having lan broadcast was an issue I faced

**Comment by PrototypeXodeus** [comment]
how do I change those LAN settings?

**Comment by PrototypeXodeus** [comment]
would this be a fix from my friends PC? remember that I am not running the alpha bedrock server locally, just the phantom-linux file.

**Comment by PrototypeXodeus** [comment]
Found the fix, it was the "LANBroadcast" set to 0 for the world. Weird quirk, especially because you can't change that value in the minecraft bedrock alpha server.

You can mark this ticket as solved

**Comment by counterfitninja** [comment]
That is the setting for visable to lan players. Was this an imported Map?

**Comment by Bullet55NL** [comment]
> Found the fix, it was the "LANBroadcast" set to 0 for the world. Weird quirk, especially because you can't change that value in the minecraft bedrock alpha server.
> 
> You can mark this ticket as solved

You're welcome :-)

**Comment by abdulman7** [comment]
It works great on my Mac! Thanks jhead for this repository
