### ISSUE TITLE
Feature Suggestion - GUI

### ISSUE THREAD

**Issue by subsaga** [jhead/phantom#86]
Hi jhead,

love the app and myself and a few friends have been using it to play on my minecraft server recently.

Some of the friends (particularly on Mac) had issues setting it up as they are not very technically incline. Could including a GUI as part of the package alleviate this? I mocked the attached up in Figma as an example.

![Phantom GUI mockup](https://user-images.githubusercontent.com/8171487/82754152-f9e56c80-9dc2-11ea-8351-66c2deab8b69.png)

Let me know if you have any comments.

Thanks

**Comment by jhead** [comment]
Hey @subsaga, cool figma! There are some community projects that wrap phantom in a GUI, but an official one is still in the works.

#22
