### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by Yberias** [jhead/phantom#89]
Hey, I want to use your "framework" but I can't establish connection by your application.

C:\Users\...\Downloads>phantom-windows server_ip:29449
Starting up with remote server IP: server_ip:29449
[90m1:37PM[0m [32mINF[0m Starting idle connection handler
[90m1:37PM[0m [32mINF[0m Binding ping server to port 19132
[90m1:37PM[0m [32mINF[0m Binding proxy server to: 0.0.0.0:60625
[90m1:37PM[0m [32mINF[0m Proxy server listening!
[90m1:37PM[0m [32mINF[0m Once your console pings phantom, you should see replies below.

And nothing else after couple of minutes.
I tried it on my local and in my mobile network the console looks the same.

On Minecraft Client on WIN10 I do not see any local servers.

Thanks for help.
Regards
Tomasz

**Comment by Yberias** [comment]
UPDATE:

I tried this application on console XBOX ONE and it is work perfectly :)
Thanks a lot, but on windows 10 and on my mobile phone, it is not appear on LAN servers when I was connected on the same wi-fi network.

Regards

**Comment by jhead** [comment]
Hey @Yberias, thanks for the report. I'll keep it in mind. The issue with Win10 might be, if you're running both phantom and the Win10 client on the same PC, Windows has some network/security peculiarities that makes phantom not show up in the server list. I've had luck running it on another PC or connecting from another device _first_, then it will show up on Win10.

As for mobile, hmmmm. I'm not sure why that would happen. If you want to share any more details about your local network setup, router, wifi network, version of phantom, and server software, etc., that might provide some info to help me narrow it down.
