### ISSUE TITLE
An issue and a request

### ISSUE THREAD

**Issue by theonemodder** [jhead/phantom#9]
The issue is when I'm on my Xbox the server shows up for a second, but than disappears. The request is if it is possible could you had switch support, on switch the server dosent even show up.

**Comment by Dawserdoos** [comment]
This tool won't work for Switch as the Nintendo Switch has no LAN support, which is how this tool feeds the server to your Xbox, however there is a DNS trick I've heard of to change one of the already existing servers in the server list to a custom one.

**Comment by jhead** [comment]
As @Dawserdoos mentioned, the Nintendo Switch isn't supported at the moment since it doesn't support LAN servers itself. We might be able to provide a DNS solution in the future, so keep an eye out for that.
