### ISSUE TITLE
phantom-linux does not connect to the server

### ISSUE THREAD

**Issue by Supergamer5465** [jhead/phantom#92]
Once I have started everything, The message below is printed in the console. However, it never connects. I have tried this on macos and when it connected a message saying that it had connected to the server was printed, but on phantom-linux nothing happens after these messages are printed. I have kept my computer on for hours, but it was always the same and never connected
 to any server that I tried.

10:16AM INF Starting idle connection handler
10:16AM INF Binding ping server to port 19132
10:16AM INF Binding proxy server to: 0.0.0.0:58477
10:16AM INF Proxy server listening!
10:16AM INF Once your console pings phantom, you should see replies below.

**Comment by jhead** [comment]
Hey @Supergamer5465, do you have any sort of firewall, iptables rules, or something similar that might be preventing your device from reaching phantom on port 19132 (UDP)? Is phantom on the same LAN as your other devices?

**Comment by Supergamer5465** [comment]
When I tried the macOS phantom it was on a different LAN, so it is probably issues with the network. I will check it out. Thank you.
