### ISSUE TITLE
Not showing on LAN (PS4)

### ISSUE THREAD

**Issue by Mineaxe** [jhead/phantom#95]
So I think I did everything right.
1. I downloaded phantom-windows.exe and phantom-0.5.1.zip
2. I launched cmd, dragged the .exe into there and added this server: RushNation.NET:19132
3. It loaded and it wrote this: (https://user-images.githubusercontent.com/67229391/85225767-c30b7200-b3d3-11ea-84b5-b74bcebad103.PNG)

I am using windows 10, phantom-0.5.1 and I am on my ps4

**Comment by lukemagdalin** [comment]
That looks correct, have you allowed phantom through the firewall when prompted during the first run?

**Comment by End3rgamer27** [comment]
Are you using phantom 0.5.1? Because I used it and it didn't work either.

**Comment by End3rgamer27** [comment]
I am also on PS4

**Comment by End3rgamer27** [comment]
Although now you can't use any phantom, because of 1.16.
I thried and 1.16 breaks it.

**Comment by lukemagdalin** [comment]
> Although now you can't use any phantom, because of 1.16.
> I tried and 1.16 breaks it.
I have been able to connect to a 1.16 server hosted from my win 10 computer from my phone.

**Comment by End3rgamer27** [comment]
> > Although now you can't use any phantom, because of 1.16.
> > I tried and 1.16 breaks it.
> 
> I have been able to connect to a 1.16 server hosted from my win 10 computer from my phone.

For me it is broken, and it has been ever since 1.16

**Comment by End3rgamer27** [comment]
> So I think I did everything right.
> 
> 1. I downloaded phantom-windows.exe and phantom-0.5.1.zip
> 2. I launched cmd, dragged the .exe into there and added this server: RushNation.NET:19132
> 3. It loaded and it wrote this: (https://user-images.githubusercontent.com/67229391/85225767-c30b7200-b3d3-11ea-84b5-b74bcebad103.PNG)
> 
> I am using windows 10, phantom-0.5.1 and I am on my ps4

Have you tried letting it through firewall?

**Comment by End3rgamer27** [comment]
Do this: [how to join servers on minecraft ps4 1.16](https://www.youtube.com/watch?v=vM9c1DOhF5M)

**Comment by End3rgamer27** [comment]
> So I think I did everything right.
> 
> 1. I downloaded phantom-windows.exe and phantom-0.5.1.zip
> 2. I launched cmd, dragged the .exe into there and added this server: RushNation.NET:19132
> 3. It loaded and it wrote this: (https://user-images.githubusercontent.com/67229391/85225767-c30b7200-b3d3-11ea-84b5-b74bcebad103.PNG)
> 
> I am using windows 10, phantom-0.5.1 and I am on my ps4

I think I found the problem: both your pc and ps4 have to be connected to LAN.
I hac the exact same problem until I did this.

**Comment by jhead** [comment]
Hey @Mineaxe, sorry for the delay! Along with the above suggestions, please make sure [this setting](https://github.com/jhead/phantom#troubleshooting) is also enabled on your server, otherwise it won't show up in the list when phantom is running.
