### ISSUE TITLE
1.16.0 not pining

### ISSUE THREAD

**Issue by End3rgamer27** [jhead/phantom#96]
Hi I'm Endergamer, and I play on the PS4. I noticed that phantom no longer works in 1.16, can you please fix this?

**Comment by Jim-Kroovy** [comment]
I'm using the latest release and it's working for Xbox One in 1.16 on Windows 10, although it takes a very long time to connect if there are resource packs on the server. Not sure if this can help but that's my 2 cents until you get reply.

**Comment by rickx7pb** [comment]
I have the same issue on ps4, since they started the new update I try to join the phantom server but it keep saying that the server outdated or something like that.

**Comment by counterfitninja** [comment]
If it says server is outdated it means the server needs to be on 1.16 as well as your client, or update the ps4 version

**Comment by End3rgamer27** [comment]
When I try to use phantom it doesn't even detect the ps4.

**Comment by End3rgamer27** [comment]
When I download phantom 0.5.1, witch files must I download?

**Comment by End3rgamer27** [comment]
I tried downloading it again and it sais:
![Screenshot (8)](https://user-images.githubusercontent.com/66774535/85916871-055e0480-b855-11ea-8562-4bc0752528c2.png)

**Comment by End3rgamer27** [comment]
> I'm using the latest release and it's working for Xbox One in 1.16 on Windows 10, although it takes a very long time to connect if there are resource packs on the server. Not sure if this can help but that's my 2 cents until you get reply.
> 
> EDIT: If cancelling after accepting the "Download Resource Packs" the LAN connection disappears in minecraft and everything needs restarting for it to work again.

Thank for the info.

**Comment by Jim-Kroovy** [comment]
I honestly feel the readme of this this Repo needs sorting out a bit so someone that is not a programmer or IT technician can actually use this and understand what it's doing.

**A few reasons it might not ping/work:** 

Your anti-virus/firewall might be blocking it

Your wifi/internet isn't very strong - I found on my brothers budget internet connection it would take up to 3 minutes to start pinging and even then it was taking in excess of 20 minutes to load him into any server.

Phantom uses port 19132 of your connection so if you are running anything else through that it won't work.

And as counterfitninja said 

> If it says server is outdated it means the server needs to be on 1.16 as well as your client

**Comment by End3rgamer27** [comment]
> I honestly feel the readme of this this repo needs sorting out a bit so someone that is not a programmer or IT technician can actually use this and understand what it's doing.
> 
> **A few reasons it might not ping/work:**
> 
> Your anti-virus/firewall might be blocking it
> 
> Your wifi/internet isn't very strong - I found on my brothers budget internet connection it would take up to 3 minutes to start pinging and even then it was taking in excess of 20 minutes to load him into any server.
> 
> Phantom uses port 19132 of your connection so if you are running anything else through that it won't work.
> 
> And as counterfitninja said
> 
> > If it says server is outdated it means the server needs to be on 1.16 as well as your client

Thank you. I will try letting it through the firewall. Bit it couldn't be anything else, because I have pretty good internet and I waited about 20 minutes. + the server has the port of 19132

**Comment by counterfitninja** [comment]
Actually seeing the same now. May be the resource pack. I'll try things later to see if I can work around it

**Comment by Jim-Kroovy** [comment]
The servers port shouldn't matter unless you are running the server on the same internet connection phantom uses - eg: If i run my server on port 19132 then i try to run phantom on the same machine the servers running on it will throw an error in the command line because ports can't multi-task like that.

And yeah anything with resource packs has been hell, it either takes hours to load or just never happens lol

**Comment by counterfitninja** [comment]
Ok i can confirm that 1.16 is not working when there are Behavior/ Resource packs to download. Its causing my Xbox Minecraft to crash. Works fine on Android and Win10

**Comment by End3rgamer27** [comment]
Should I allow phantom through private and public or just private firewall?

**Comment by jhead** [comment]
>I honestly feel the readme of this this repo needs sorting out a bit so someone that is not a programmer or IT technician can actually use this and understand what it's doing.

Hey @Jim-Kroovy, I would appreciate PRs to update the readme to be more clear if you feel so inclined 😄 

> Should I allow phantom through private and public or just private firewall?

@End3rgamer27, you can do both to be safe but it should be just Private.

**Comment by jhead** [comment]
For anyone using a resource pack, can you send me a link to the packs you're using so that I can test? @Jim-Kroovy @counterfitninja 

I've actually never tested phantom with a resource pack but I can imagine why this is happening, since the resource pack data would be sent through your PC, through phantom, to your Xbox/PS4, which could be very slow. There might be some optimizations I can do to improve that.

**Comment by counterfitninja** [comment]
I currently have a world with the trulybedrock pack on it. Not tested anything else.

https://www.trulybedrock.com/season-2/ is a link you can grab it. Mi e does not takes ages, it actually crashes Minecraft. I can test other maps tomorrow.

**Comment by Jim-Kroovy** [comment]
Yeah, i haven't been able to test my own server with phantom on my end as i'm running my server on 19132, but i know that my resource pack kills Minecraft for my brother when he tries to get on and it's only a work in progress 75kb re-texture of the armour.

I do have some pretty decent random spawning functions that i've written installed, but as i understand it behaviour packs should be running on the server not on the client?

Anyway here's the little armour retex.

[Acceptable.zip](https://github.com/jhead/phantom/files/4842946/Acceptable.zip)

**Comment by End3rgamer27** [comment]
> @End3rgamer27, you can do both to be safe but it should be just Private.
Thank you. I have let it through, but it still doesn't show up on LAN.

**Comment by End3rgamer27** [comment]
I have 1 internet, but 2 modems. I use one modem for pc and one for ps4. Could this be the problem?

**Comment by imnotjack91** [comment]
based on your description, is it safe to assume you meant 1 modem and 2 routers?
(modems are the entry point where internet from ISP is converted from fiber, coax or DSL into rj45 / ethernet effectively hosting an over-arching network)
(routers host networks and/or route the traffic to other networks and send traffic to the internet via the modem)
if my assumption is correct then we will need more details about exactly how this is mapped.

**Comment by imnotjack91** [comment]
as an example. i have my "modem/gateway" connecting to my fibre connection. it has a built in switch so i have a fortinet router plugged in that i connect my server to. also connected to my modem/gateway is my personal router that hosts my wifi, gaming and smart equipment. i have my public ip address forwarded to my fortinet router so my personal network is invisible to incoming traffic. so i will put my network map like this: 
modem>router1, router2<
router1>switch,  1 laptop, 4 phones, roku, 3 ipads
switch>desktop, printer, xbox, 3 laptops<
router2>server, NAS, Terminal server<
NAT is turned off on router1
firewall is completely closed on router1
multiple server ports are opened on router2
switch is unmanaged

**Comment by End3rgamer27** [comment]
> based on your description, is it safe to assume you meant 1 modem and 2 routers?
> (modems are the entry point where internet from ISP is converted from fiber, coax or DSL into rj45 / ethernet effectively hosting an over-arching network)
> (routers host networks and/or route the traffic to other networks and send traffic to the internet via the modem)
> if my assumption is correct then we will need more details about exactly how this is mapped.

No, I have 2 modems that are different and 1 internet, that is the same for both modems. At least that is what y dad told me.

**Comment by imnotjack91** [comment]
ok. do you know how the 2 modems are sharing the same ISP? it is technically impossible for 2 "modems" to share the same ISP 
UNLESS: 1 modem has a built in switch and is not being used as a MODEM but is being used for its ROUTER capabilities. 
im not going to say your dad is wrong just yet and im not going to say hes using incorrect terminology, but what hes saying isnt making sense to someone who lives and breaths this stuff. this is where that network map i made an example of will come in handy. so the questions im looking to answer are the following:
1. which modem communicates with  the ISP? (internet service provider)
2. how is the second modem getting internet if there is only 1 internet connection? 
3. is the second modem acting as a slave (or access point) of the 1st modem?
4. Is it possible that what we are calling a "modem" is actually a router and we are just mixing up terminology? 
(it really sounds like number 4 is the most likely scenario and I'm trying really hard not to be disrespectful about it as i know, work with and support so many people who get the 2 mixed up on a DAILY basis)
but again, please try to recreate a map of your network (dont provide your public ip address on any forums EVER)

**Comment by End3rgamer27** [comment]
> ok. do you know how the 2 modems are sharing the same ISP? it is technically impossible for 2 "modems" to share the same ISP
> UNLESS: 1 modem has a built in switch and is not being used as a MODEM but is being used for its ROUTER capabilities.
> im not going to say your dad is wrong just yet and im not going to say hes using incorrect terminology, but what hes saying isnt making sense to someone who lives and breaths this stuff. this is where that network map i made an example of will come in handy. so the questions im looking to answer are the following:
> 
> 1. which modem communicates with  the ISP? (internet service provider)
> 2. how is the second modem getting internet if there is only 1 internet connection?
> 3. is the second modem acting as a slave (or access point) of the 1st modem?
> 4. Is it possible that what we are calling a "modem" is actually a router and we are just mixing up terminology?
>    (it really sounds like number 4 is the most likely scenario and I'm trying really hard not to be disrespectful about it as i know, work with and support so many people who get the 2 mixed up on a DAILY basis)
>    but again, please try to recreate a map of your network (dont provide your public ip address on any forums EVER)

ok, so I asked my dad and here's what he said:
one receives internet, transfers it to the other and the other one send out the signal.

**Comment by imnotjack91** [comment]
ok. and is the server/host on the main modem or the secondary modem (acting as router)?

**Comment by End3rgamer27** [comment]
my private ip is: 192.168.1.76 
(I ran cmd and typed ipconfig)

**Comment by End3rgamer27** [comment]
Here is what I got after running ipconfig (it is in Italian)
Windows IP Configuration                                                                                                                                                                              Ethernet adapter Connessione alla rete locale (LAN):                                                                                   
Media State . . . . . . . . . . . : Media disconnected            
Connection-specific DNS Suffix  . : 
                                                                                             
Wireless LAN adapter Connessione alla rete locale (LAN)* 11:                                                                           
Media State . . . . . . . . . . . : Media disconnected            
Connection-specific DNS Suffix  . :
                                                                                              
Wireless LAN adapter Connessione alla rete locale (LAN)* 12:                                                                          
 Media State . . . . . . . . . . . : Media disconnected            Connection-specific DNS Suffix  . :                                                                                              Wireless LAN adapter Wi-Fi:    
                                                                                                        
Connection-specific DNS Suffix  . :                               
Link-local IPv6 Address . . . . . : fe80::e0b3:d62:3b7f:8a52%14   
IPv4 Address. . . . . . . . . . . : 192.168.1.76                  
Subnet Mask . . . . . . . . . . . : 255.255.255.0                 
Default Gateway . . . . . . . . . : 192.168.1.251

**Comment by jhead** [comment]
Hey @End3rgamer27, it's tough to troubleshoot without knowing exactly how your LAN + wifi + any devices like routes are setup on the network. If your PS4 isn't seeing phantom _at all_, that would suggest that your PS4 and phantom device (PC) are not on the same LAN. Depending on your network setup, this could happen if your PC is hardwired while the PS4 is on wifi, or vice versa.

**Comment by End3rgamer27** [comment]
Thank you, this could be the problem
I am moving both of them to a LAN cable soon, and I will see if that works.

**Comment by End3rgamer27** [comment]
Could the problem be that my ps4 is jailbroken?
I don't know if it's jailbroken for sure, but it might be.

**Comment by End3rgamer27** [comment]
OK, I think I found the problem:
My ps4 is jailbrkoken.
I'm not 100% sure, but I think it is.
Does anybody know how to un-jailbreak it without deleting data?

**Comment by joshuaxlino** [comment]
> OK, I think I found the problem:
> 
> My ps4 is jailbrkoken.
> 
> I'm not 100% sure, but I think it is.
> 
> Does anybody know how to un-jailbreak it without deleting data?

The jailbreak should not be the problem. It is most likely a connection problem. Does the jailbreak change anything like connection methods or have more network settings? You can also try if you have a second device with minecraft (win10,ios,androidOS) and see if it pings.

**Comment by End3rgamer27** [comment]
I don't know if the ps4 is broken, but on my windows pc I have minecraft
bedrock, and it doesn't ping either.

**Comment by joshuaxlino** [comment]
Add me on discord, i may be able to help you there. JereyX#1823

**Comment by End3rgamer27** [comment]
I do not have a discord account.

**Comment by End3rgamer27** [comment]
> I don't know if the ps4 is broken, but on my windows pc I have minecraft bedrock, and it doesn't ping either.

Also the pc I have minecraft bedrock on is the same pc I am running phantom on.

**Comment by End3rgamer27** [comment]
I finaly fixed the roblem!😄!  I moved both the ps4 and the pc to LAN, and then it worked. Thank you all for your help, and have a wonderfull day!
