### ISSUE TITLE
How would I use this or similar technology for a phone?

### ISSUE THREAD

**Issue by USBCharger** [jhead/phantom#99]
I don't remember posting anything on GitHub before as the entire site still confuses me a little, so apologies if this is in the wrong place but nonetheless, here we go. I see you have software for windows, mac, and Linux. That's amazing. However, I was wondering how someone who doesn't have a computer can turn their phone into a proxy server to connect to a server. There are (not a ton, but a some) who use discord (the place I'm advertising my Java/bedrock cross-platform server) that has a phone, yet not a computer. I'm almost positive that theoretically if windows can be turned into a proxy server, they should be able to as well. I know that some software to do such things exists, however, I don't believe it'll make the LAN game come up. If you could please offer me some help as to how Andriod/iPhone users could do this, it'd be much appreciated.

**Comment by imnotjack91** [comment]
there is another thread on the topic of using android as a proxy server. he has compiled arm versions of this program specifically for that use case.

**Comment by imnotjack91** [comment]
idk about using iphone as any code run on it would need to be run from an app in the app store. maybe a future version of this code could be run as an app that basically uses "web app" like features. id be curious if someone could make a webapp specifically for use with all devices. that would be cool.
